# Generated by Django 4.0.5 on 2022-12-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
