# Generated by Django 4.0.5 on 2022-12-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Books',
            new_name='books',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujarat', 'Gujarat'), ('Maharastra', 'Maharastra'), ('Rajsthan', 'Rajsthan'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka')], max_length=350),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Accepted ', 'Accepted'), ('Packed ', 'Packed'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('cancelled', 'cancelled')], default='Pending', max_length=200),
        ),
    ]
