# Generated by Django 4.0.5 on 2022-12-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_books_orders_books_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='books',
            new_name='book',
        ),
    ]
