# Generated by Django 4.0.5 on 2023-01-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_author_publisher_alter_books_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
    ]
