# Generated by Django 4.0.5 on 2023-01-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_books_author_remove_books_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.publisher'),
            preserve_default=False,
        ),
    ]
