# Generated by Django 4.0.5 on 2023-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_books_author_books_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': 'Publisher'},
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default='abc'),
        ),
    ]
