# Generated by Django 4.0.5 on 2023-03-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_publisher_options_books_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='book',
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.cart'),
            preserve_default=False,
        ),
    ]
