# Generated by Django 4.0.5 on 2023-03-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_orders_book_orders_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
